# Site settings
title: Santi Achinelli
description: Santi's Slice of the Internet
# baseurl:
# url: "achinelli.com"

# User settings
username: Santi Achinelli
user_description:
user_title: Bootstrapper Extraordinaire
email: santi@achinelli.com


exclude: ['package.json', 'src' , 'node_modules']
